In [1]:
import pandas as pd

In [41]:
train = pd.read_csv(r"E:\12. githubR\pfs_kaggle\pfs_kaggle\data\sales_train_v2.csv")
test = pd.read_csv(r"E:\12. githubR\pfs_kaggle\pfs_kaggle\data\test.csv",index_col="ID")
sub = pd.read_csv(r"E:\12. githubR\pfs_kaggle\pfs_kaggle\data\sample_submission.csv",index_col="ID")
shop = pd.read_csv(r"E:\12. githubR\pfs_kaggle\pfs_kaggle\data\shops.csv")
item_categories = pd.read_csv(r"E:\12. githubR\pfs_kaggle\pfs_kaggle\data\item_categories.csv")
items = pd.read_csv(r"E:\12. githubR\pfs_kaggle\pfs_kaggle\data\items.csv")

In [42]:
train = train.sort_values(by=["date_block_num","shop_id","item_id"])

In [49]:
train_m = pd.DataFrame(train.head(1))
for i in train.index[1:1000]:
    if train.loc[i,"shop_id"] == train_m.iloc[-1]["shop_id"] and train.loc[i,"item_id"] == train_m.iloc[-1]["item_id"] and train.loc[i,"date_block_num"] == train_m.iloc[-1]["date_block_num"]:
        train_m.iloc[-1]["item_cnt_day"] += train.loc[i,"item_cnt_day"]
    else:
        train_m = train_m.append(train.loc[i,:])
train_m

D:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

             date  date_block_num  shop_id  item_id  item_price  item_cnt_day
40085  03.01.2013               0        0       32       221.0           2.0
40089  03.01.2013               0        0       33       347.0           1.0
40092  31.01.2013               0        0       35       247.0           1.0
40095  31.01.2013               0        0       43       221.0           1.0
40093  13.01.2013               0        0       51       130.0           1.0
40097  10.01.2013               0        0       61       195.0           1.0
40110  17.01.2013               0        0       75        76.0           1.0
40098  16.01.2013               0        0       88        76.0           1.0
40056  06.01.2013               0        0       95       193.0           1.0
40057  10.01.2013               0        0       96        70.0           1.0
40055  31.01.2013               0        0       98       268.0           1.0
40058  17.01.2013               0        0      111        89.0           1.0
40059  11.01.2013               0        0      149        99.0           1.0
40062  16.01.2013               0        0      151        75.0           1.0
40063  09.01.2013               0        0      153       258.0           1.0
40064  10.01.2013               0        0      198       112.0           1.0
40065  05.01.2013               0        0      210       118.0           1.0
40067  04.01.2013               0        0      282       109.0           1.0
40068  22.01.2013               0        0      306        59.0           1.0
40069  21.01.2013               0        0      351        89.0           1.0
40070  07.01.2013               0        0      421       162.0           1.0
40071  31.01.2013               0        0      438       162.0           1.0
40072  09.01.2013               0        0      482      1360.0           1.0
40074  09.01.2013               0        0      484       124.0           1.0
40078  27.01.2013               0        0      491       361.0           1.0
40079  19.01.2013               0        0      498       124.0           1.0
40096  15.01.2013               0        0      556        90.0           3.0
40144  06.01.2013               0        0      642        90.0           1.0
40150  09.01.2013               0        0      651        90.0           1.0
40157  18.01.2013               0        0      657        90.0           1.0
...           ...             ...      ...      ...         ...           ...
39761  26.01.2013               0        0     3961       285.0           1.0
39762  29.01.2013               0        0     3965       175.0           1.0
39763  25.01.2013               0        0     3976       219.0           1.0
39764  23.01.2013               0        0     3980       219.0           1.0
39766  28.01.2013               0        0     3983       190.0           1.0
39767  28.01.2013               0        0     4006       180.0           1.0
39768  09.01.2013               0        0     4013       161.0           1.0
39765  10.01.2013               0        0     4036       483.0           1.0
40995  09.01.2013               0        0     4072       190.0           1.0
40996  26.01.2013               0        0     4076       173.0           1.0
41084  22.01.2013               0        0     4092       190.0           1.0
41085  16.01.2013               0        0     4100       282.0           1.0
41087  05.01.2013               0        0     4110       190.0           1.0
39769  11.01.2013               0        0     4127       816.0           1.0
39774  08.01.2013               0        0     4128       612.0           1.0
39781  04.01.2013               0        0     4147      1496.0           1.0
39935  03.01.2013               0        0     4148      1047.0           1.0
40407  08.01.2013               0        0     4163      1088.0           4.0
41023  29.01.2013               0        0     4164       707.0           2.0
41022  18.01.2013               0        0     4167      1856.0           1.0
41020  28.01.2013               0        0     4211      1353.0           1.0
40997  05.01.2013               0        0     4227       734.0           1.0
41000  05.01.2013               0        0     4229      1227.0           1.0
41001  30.01.2013               0        0     4240      1469.0           2.0
41002  18.01.2013               0        0     4241      1145.0           1.0
41004  13.01.2013               0        0     4244      1460.0           1.0
41005  17.01.2013               0        0     4248      1469.0           1.0
41009  03.01.2013               0        0     4249      1460.0           2.0
41036  04.01.2013               0        0     4251       263.0           1.0
41052  31.01.2013               0        0     4252       394.0           1.0

[380 rows x 6 columns]